CATEGORY_MAX_LEN_NAME_SIZE = 256
CATEGORY_MAX_LEN_SLUG_SIZE = 50
GENRE_MAX_LEN_NAME_SIZE = 256
GENRE_MAX_LEN_SLUG_SIZE = 50
TITLE_MAX_LEN_SLUG_SIZE = 256
MIN_VALUE_YEAR = 0
MIN_SCORE_VALUE = 1
MAX_SCORE_VALUE = 10
