# Generated by Django 3.2 on 2024-05-08 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240508_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такое имя уже существует!'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Это поле может содержать только буквы, цифры и @, ., +, -, _ знаки')], verbose_name='username'),
        ),
    ]
