# Generated by Django 3.2 on 2024-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240510_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
    ]
